### ISSUE TITLE
Show Hide Code in Navigation.md

### ISSUE THREAD

**Issue by mubix** [pwnwiki/pwnwiki.github.io#40]
Now that scripts are allowed in the navigation.md lets look at moving the show/hide code up to it.

RE: https://github.com/Dynalon/mdwiki/releases/tag/0.6.1

**Comment by tekwizz123** [comment]
Any update on this? Just had to add this to another page myself to get some content to remain hidden. Would be good if we could fix this seeing as this is going on 3 years old now.

**Comment by WebBreacher** [comment]
Actually, @mubix and I and others on the pwnwiki team tried to move the pwnwiki to another platform totally. So, I'd say you can close this issue as our new platform will have new features.

**Comment by tekwizz123** [comment]
Okay closing this issue for now under the assumption the new platform will have features to address this.
